version: "3.7"
services:
  frontend:
    build:
      context: ./frontend/docker
      dockerfile: development/nginx/Dockerfile
    ports:
      - "8080:443"
    volumes:
      - ./frontend:/app
      - ./frontend/docker/common/nginx/conf.d/ssl:/etc/nginx/ssl
    depends_on:
      - frontend-node

  frontend-node:
    build:
      context: frontend/docker/development/node
    environment:
      WDS_SOCKET_PORT: 0
    volumes:
      - ./frontend:/app
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn start"
    tty: true

  frontend-node-cli:
    build:
      context: frontend/docker/development/node
    volumes:
      - ./frontend:/app

  api:
    build:
      context: ./api/docker
      dockerfile: development/nginx/Dockerfile
    # links:
      # - api-php-fpm
    ports:
      - "8081:443"
    volumes:
      - ./api:/app
      - ./api/docker/common/nginx/conf.d/ssl:/etc/nginx/ssl
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: ./api/docker
      dockerfile: development/php-fpm/Dockerfile
    # links:
      # - api-postgres
      # - redis
      # - elasticsearch
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_IDE_CONFIG: serverName=API
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: app
      REDIS_PORT: 6379
      REDIS_HOST: redis
      ELASTICSEARCH_HOSTS: elasticsearch:9200
    volumes:
      - ./api:/app
    depends_on:
      - api-postgres
      - redis
      - elasticsearch

  api-php-cli:
    build:
      context: ./api/docker
      dockerfile: development/php-cli/Dockerfile
    # links:
      # - api-postgres
      # - redis
      # - elasticsearch
    environment:
      # APP_ENV: dev
      APP_DEBUG: 1
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: app
      REDIS_PORT: 6379
      REDIS_HOST: redis
      ELASTICSEARCH_HOSTS: elasticsearch:9200
      # PHP_IDE_CONFIG: serverName=API
    volumes:
      - ./api:/app

    # depends_on:
      # - api-postgres
      # - redis
      # - elasticsearch

  api-node:
    build:
      context: api/docker/development/node
    volumes:
      - ./api:/app
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn start"
    tty: true

  api-node-cli:
    build:
      context: api/docker/development/node
    volumes:
      - ./api:/app

  api-postgres:
    image: postgres:alpine3.18
    environment:
        POSTGRES_USER: app
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: app
    volumes:
        - api-postgres:/var/lib/postgresql/data
    ports:
        - "54321:5432"

  mailer:
      image: mailhog/mailhog
      ports:
        - "8082:8025"

  redis:
      image: redis:alpine3.18
      ports:
        - "63791:6379"

  elasticsearch:
      image: elasticsearch:8.9.1
      environment:
          - bootstrap.memory_lock=true
          - ES_JAVA_OPTS=-Xms128m -Xmx128m
          - xpack.security.enabled=false
          - discovery.type=single-node
          # - discovery.zen.ping.multicast.enabled=false
          # - action.auto_create_index=true
      ulimits:
          memlock:
              soft: -1
              hard: -1
      volumes:
          - elasticsearch:/var/lib/elasticsearch/data
      ports:
          - "9201:9200"

volumes:
  api-postgres:
  elasticsearch:
  redis:
  mailer:
